format = """\
$time$cmd_duration
$directory$git_branch$git_status$character\
"""

[directory]
truncation_length=8
truncation_symbol = 'â€¦/'
before_repo_root_style='bold bright-black'
repo_root_style='bold cyan'
style='bold bright-black'
read_only=' [read-only]'
read_only_style='bold red'

[time]
disabled = false
format = '[\[time:[$time](bold cyan)\]](bold bright-black)'

[cmd_duration]
min_time = 0
show_milliseconds = true
format = '[\[took:[$duration](bold cyan)\]](bold bright-black)'

[git_branch]
format='[$branch(:$remote_branch)]($style)'

[git_status]
format='([\[$all_status$ahead_behind\]]($style)) '
